// Part of the Spicy3D Project, derived from Chili3D, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

// GENERATED by scripts/generate-cloud-api.mjs from packages/cloud/openapi.json — do not edit.
// Regenerate with `npm run cloud:api` (or `npm run cloud:api -- <path-or-url>` for a newer spec).

export interface paths {
    "/api/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last successful backup (with a stale warning) and disk usage of the blob and backup volumes. */
        get: operations["AdminGetSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All accounts, oldest first. */
        get: operations["AdminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete an account and all its data. */
        delete: operations["AdminDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable an account: it can't sign in, all its sessions end immediately and its access tokens are revoked. */
        post: operations["AdminDisableUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a disabled account (also clears a sign-in lockout). */
        post: operations["AdminEnableUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a password reset link to hand to the user (the recovery path when the server can't send email). */
        post: operations["AdminCreatePasswordResetLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-email-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply an email change with the token sent to the new address; signs out all sessions and revokes all access tokens. */
        post: operations["ConfirmEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a password reset link. Always 202 (doesn't reveal whether the account exists); 503 email_disabled when the server can't send email. */
        post: operations["ForgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password; sets the session cookie. 5 failed attempts lock the account for 15 minutes (answered like a wrong password: 401 invalid_credentials). */
        post: operations["LogIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session and clear the cookie. */
        post: operations["LogOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send the verification email again to the signed-in user. */
        post: operations["ResendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token; signs out all sessions and revokes all access tokens. */
        post: operations["ResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account. Signs in (201) unless email verification is required (202, also returned for an already registered email). */
        post: operations["SignUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the email address with the token from the verification email. */
        post: operations["VerifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blobs/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A blob referenced by one of the caller's versions. Immutable: cacheable forever; gzip-encoded when the client accepts it. */
        get: operations["GetBlob"];
        /** Upload a blob (raw bytes, uncompressed; the URL is the SHA-256 of the content, lowercase hex). Streamed and verified; at most the server's upload limit (413) and within the caller's quota (507). */
        put: operations["UploadBlob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blobs/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Which of these blobs the caller still has to upload before referencing them in a save. */
        post: operations["CheckBlobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public server configuration for the client: version, feature flags and endpoint URLs. */
        get: operations["GetConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's documents, most recently updated first (keyset pagination). trash=true lists the trash instead; q filters by name. */
        get: operations["ListDocuments"];
        put?: never;
        /** Create a document with its first version. Optional Idempotency-Key header: a retry within 24 hours returns the document instead of 409. */
        post: operations["CreateDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document metadata and its head version. The ETag is the head version id, to send as If-Match when saving. */
        get: operations["GetDocument"];
        put?: never;
        post?: never;
        /** Move to the trash; purged permanently after the server's retention period (see /api/config). */
        delete: operations["TrashDocument"];
        options?: never;
        head?: never;
        /** Rename (metadata only, last write wins, no new version). */
        patch: operations["RenameDocument"];
        trace?: never;
    };
    "/api/documents/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore from the trash. */
        post: operations["RestoreDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history, newest first (keyset pagination), optionally of one kind. */
        get: operations["ListVersions"];
        put?: never;
        /** Save a new head version. Requires If-Match with the current head (409 version_conflict with the head otherwise); upload blobs first (422 blobs_missing). Optional Idempotency-Key header: a retry within 24 hours returns the original version. */
        post: operations["SaveVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency status. */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's profile. */
        get: operations["GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the display name. */
        patch: operations["UpdateMe"];
        trace?: never;
    };
    "/api/me/change-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the email address. With email enabled a confirmation link goes to the new address (202); without email the change applies immediately as unverified (200). Once applied, all other sessions are signed out and all access tokens revoked. */
        post: operations["ChangeEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the password; signs out all other sessions and revokes all access tokens. */
        post: operations["ChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently delete the account and all its data (documents, versions, settings, sessions), confirmed with the current password. Immediate; signs out everywhere. With email enabled the address gets a notice. */
        post: operations["DeleteAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download all data of the account as a ZIP (streamed): account.json, and per document the latest version as a .spicy file, with history=true every kept version too. Once per hour. */
        get: operations["ExportAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's active sessions, most recently used first. */
        get: operations["GetSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign a session out. Revoking the current session also clears its cookie. */
        delete: operations["RevokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's settings; defaults for everything never set. The ETag can be sent back as If-Match when saving. */
        get: operations["GetSettings"];
        /** Replace the settings: absent keys take their defaults, unknown keys are rejected (400). With If-Match, 412 when they were changed on another device since; without it the last write wins. The user's other devices are notified (settings.updated). */
        put: operations["UpdateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's cloud storage use and quota. */
        get: operations["GetStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's access tokens that aren't revoked (expired ones included), newest first. Secrets are never returned. */
        get: operations["ListAccessTokens"];
        put?: never;
        /** Create an access token, confirmed with the current password; at most 50 active per user (409 too_many_tokens). The response contains the secret, which is shown only this once. Use it as Authorization: Bearer <token> on /mcp, or with documents:read on the read-only document endpoints. */
        post: operations["CreateAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an access token: it stops working at once and its MCP sessions end. */
        delete: operations["RevokeAccessToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The version's manifest (JSON as uploaded). Immutable: cacheable forever; gzip-encoded when the client accepts it. */
        get: operations["GetVersionManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set or clear the label, pin or unpin. Content is immutable. */
        patch: operations["UpdateVersion"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            /**
             * Format: date-time
             * @description Creation time (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Expiry (UTC); `null`: never expires. An expired token no longer works.
             */
            expiresAt: string;
            /**
             * Format: uuid
             * @description Token id.
             */
            id: string;
            /**
             * Format: date-time
             * @description Last use (UTC, minute resolution); `null` if never used.
             */
            lastUsedAt: string;
            /** @description Label given when it was created. */
            name: string;
            /** @description The secret's first characters, to recognize it. */
            prefix: string;
            /** @description What the token may do. */
            scopes: string[];
        };
        AdminSystemResponse: {
            /** @description Last successful backup. */
            backup: components["schemas"]["BackupStatusResponse"];
            /** @description File systems holding the blobs and the backups (the database disk isn't visible to the API). */
            disks: components["schemas"]["DiskUsageResponse"][];
        };
        AdminUserList: {
            /** @description The requested page (`offset`, `limit` ≤ 200). */
            items: components["schemas"]["AdminUserResponse"][];
            /**
             * Format: int32
             * @description Number of accounts.
             */
            total: number;
        };
        AdminUserResponse: {
            /**
             * Format: date-time
             * @description Account creation (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the account was disabled (UTC); `null` when enabled.
             */
            disabledAt: string;
            /** @description Display name. */
            displayName: string;
            /** @description Email address. */
            email: string;
            /** @description Whether the email address is verified. */
            emailVerified: boolean;
            /**
             * Format: uuid
             * @description User id.
             */
            id: string;
            /** @description Whether the user is an administrator. */
            isAdmin: boolean;
            /**
             * Format: date-time
             * @description Last authenticated request (UTC); `null` if never signed in.
             */
            lastSeenAt: string;
            /**
             * Format: date-time
             * @description End of a sign-in lockout after failed attempts (UTC); `null` when not locked.
             */
            lockedOutUntil: string;
            /**
             * Format: int64
             * @description Bytes of cloud storage used (unique blobs, uncompressed; counts towards the quota).
             */
            storageUsed: number;
        };
        /**
         * @description Autosave pruning, relative to now (UTC buckets). Manual, merge, restore, MCP, labeled and pinned versions and the
         *     head are kept forever.
         */
        AutosaveRetentionPolicy: {
            /**
             * Format: int32
             * @description Up to this age, the last autosave of each UTC day is kept; older autosaves are deleted.
             */
            dailyDays: number;
            /**
             * Format: int32
             * @description Up to this age, the last autosave of each UTC hour is kept.
             */
            hourlyDays: number;
            /**
             * Format: int32
             * @description Every autosave younger than this is kept.
             */
            keepAllHours: number;
        };
        AutosaveSettings: {
            /** @default true */
            enabled: boolean;
            /**
             * Format: int32
             * @default 5
             */
            intervalMinutes: number;
        };
        BackupStatusResponse: {
            /** @description Whether this server reads a backup status (`Backup:StatusFile`). */
            configured: boolean;
            /**
             * Format: int64
             * @description How long it took.
             */
            durationSeconds: number | null;
            /**
             * Format: date-time
             * @description End of the last successful backup (UTC); `null` when none is recorded.
             */
            lastSuccessAt: string;
            /**
             * Format: int32
             * @description Age after which a backup is stale.
             */
            maxAgeHours: number;
            /** @description That backup's name in the backup target (argument of `deploy/restore.sh`). */
            name: null | string;
            /**
             * Format: int64
             * @description Its size: database dump plus blob snapshot.
             */
            sizeBytes: number | null;
            /** @description No successful backup within `MaxAgeHours`: show a warning. */
            stale: boolean;
        };
        BlobCheckRequest: {
            /** @description SHA-256 hashes to check (≤ 1 000). */
            hashes: string[];
        };
        BlobCheckResponse: {
            /** @description The hashes the caller must upload before referencing them. */
            missing: string[];
        };
        ChangeEmailRequest: {
            currentPassword: string;
            newEmail: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ConfigResponse: {
            /** @description Version of the HTTP contract. */
            apiVersion: string;
            /** @description WebSocket of real-time events for the signed-in user (SRV-07). */
            eventsSocket: string;
            /** @description Enabled features. */
            features: components["schemas"]["FeatureFlags"];
            mcp: null | components["schemas"]["McpConfig"];
            /** @description Origin the app is served from, without trailing slash. */
            publicUrl: string;
            /**
             * Format: date-time
             * @description Current server time (UTC), lets clients detect clock skew.
             */
            serverTime: string;
            /** @description Cloud storage limits. */
            storage: components["schemas"]["StorageLimits"];
            /** @description Server version, e.g. `0.0.1`. */
            version: string;
        };
        ConfirmEmailChangeRequest: {
            /** @description The new email address, from the confirmation link. */
            email: string;
            /** @description From the confirmation link. */
            token: string;
            /**
             * Format: uuid
             * @description From the confirmation link.
             */
            userId: string;
        };
        CreateAccessTokenRequest: {
            /** @description The account's password, to confirm (403 invalid_password or account_locked otherwise). */
            currentPassword: string;
            /**
             * Format: int32
             * @description 30, 90 or 365 days, or 0 for never; omitted: 90.
             */
            expiresInDays: number | null;
            /** @description Label, e.g. "Claude Code on my laptop" (1-100 characters). */
            name: string;
            /** @description At least one of mcp:read (MCP read tools and screenshots), mcp:write (MCP editing tools), documents:read (cloud documents and history, read-only). */
            scopes: string[];
        };
        CreatedAccessTokenResponse: {
            /**
             * Format: date-time
             * @description Creation time (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Expiry (UTC); `null`: never expires.
             */
            expiresAt: string;
            /**
             * Format: uuid
             * @description Token id.
             */
            id: string;
            /** @description Label. */
            name: string;
            /** @description The secret's first characters. */
            prefix: string;
            /** @description What the token may do. */
            scopes: string[];
            /** @description The secret (`spicy_pat_…`). Shown only this once: the server stores only a hash. */
            token: string;
        };
        CreateDocumentRequest: {
            /** @description Client-chosen id (nanoid): 1–64 characters of `A–Z a–z 0–9 _ -`, unique among the caller's documents. */
            id: string;
            /** @description Display name, 1–200 characters. */
            name: string;
            /** @description The first version (no parents; kind `manual`, `auto` or `mcp`). */
            version: components["schemas"]["NewVersionRequest"];
        };
        DeleteAccountRequest: {
            currentPassword: string;
        };
        DiskUsageResponse: {
            /**
             * Format: int64
             * @description Space available to the server.
             */
            freeBytes: number;
            /** @description `blobs` or `backups`. */
            name: string;
            /**
             * Format: int64
             * @description Size of the file system.
             */
            totalBytes: number;
            /** @description At least 80 % used. */
            warning: boolean;
        };
        DocumentList: {
            /** @description The page, most recently updated first. */
            items: components["schemas"]["DocumentSummary"][];
            /** @description Pass as `cursor` for the next page; `null` on the last page. */
            nextCursor: null | string;
        };
        DocumentResponse: {
            /**
             * Format: date-time
             * @description Creation (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When moved to the trash (UTC).
             */
            deletedAt: string;
            head: null | components["schemas"]["VersionResponse"];
            /**
             * Format: uuid
             * @description Latest version; also the `ETag`.
             */
            headVersionId: null | string;
            /** @description Document id. */
            id: string;
            /** @description Display name. */
            name: string;
            /**
             * Format: int64
             * @description Size of the latest version.
             */
            sizeBytes: number;
            /** @description Thumbnail blob, if any. */
            thumbnailSha256: null | string;
            /**
             * Format: date-time
             * @description Last save, rename, trash or restore (UTC).
             */
            updatedAt: string;
        };
        DocumentSummary: {
            /**
             * Format: date-time
             * @description Creation (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When moved to the trash (UTC); `null` when not in the trash.
             */
            deletedAt: string;
            /**
             * Format: uuid
             * @description Latest version.
             */
            headVersionId: null | string;
            /** @description Document id. */
            id: string;
            /** @description Display name (the server's copy is authoritative for listings). */
            name: string;
            /**
             * Format: int64
             * @description Size of the latest version (manifest and blobs, uncompressed).
             */
            sizeBytes: number;
            /** @description Thumbnail blob, if any (`GET /api/blobs/{sha256}`). */
            thumbnailSha256: null | string;
            /**
             * Format: date-time
             * @description Last save, rename, trash or restore (UTC).
             */
            updatedAt: string;
        };
        FeatureFlags: {
            /** @description The server can send email. When `false`, forgot-password and resend-verification answer `email_disabled` (the user should contact the administrator) and email changes apply immediately, unverified. */
            email: boolean;
            /** @description A verified email address is required to use cloud storage. */
            emailVerification: boolean;
            /** @description The remote MCP relay is enabled. */
            mcp: boolean;
            /** @description Anyone can create an account. */
            signup: boolean;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        HealthResponse: {
            /**
             * Format: date-time
             * @description When the checks ran (UTC).
             */
            checkedAt: string;
            /** @description Status per dependency, e.g. `database`. */
            checks: {
                [key: string]: components["schemas"]["HealthState"];
            };
            /** @description Overall status. */
            status: components["schemas"]["HealthState"];
            /** @description Server version. */
            version: string;
        };
        /** @enum {unknown} */
        HealthState: "healthy" | "degraded" | "unhealthy";
        HttpValidationProblemDetails: {
            detail?: null | string;
            errors?: {
                [key: string]: string[];
            };
            instance?: null | string;
            /** Format: int32 */
            status?: number | null;
            title?: null | string;
            type?: null | string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        McpConfig: {
            /** @description MCP Streamable HTTP endpoint for MCP clients. */
            endpoint: string;
            /** @description WebSocket the signed-in Spicy3D tab connects to. */
            pageSocket: string;
        };
        MeResponse: {
            /**
             * Format: date-time
             * @description When the account was created (UTC).
             */
            createdAt: string;
            /** @description Name shown in the app. */
            displayName: string;
            /** @description Email address, also used to sign in. */
            email: string;
            /** @description Whether the email address is verified. When the server requires verification, cloud storage is unavailable until it is. */
            emailVerified: boolean;
            /**
             * Format: uuid
             * @description User id (UUIDv7).
             */
            id: string;
            /** @description Roles, e.g. `admin`. */
            roles: string[];
        };
        NewVersionRequest: {
            /** @description SHA-256 of every blob the manifest references (≤ 10 000). All must be uploaded by the caller or referenced by their versions. */
            blobs: null | string[];
            /** @description Id of the saving client instance (≤ 100 characters), echoed in real-time events. */
            clientId: null | string;
            /** @description Name of the saving device (≤ 100 characters), shown in the history. */
            deviceName: null | string;
            /**
             * Format: int32
             * @description Client document format of the manifest (≥ 1).
             */
            formatVersion: number;
            kind: null | components["schemas"]["VersionKind"];
            /** @description Optional label (≤ 200 characters); labeled versions are never pruned. */
            label: null | string;
            /** @description SHA-256 of the manifest blob (uploaded first); at most the server's manifest size limit. */
            manifestSha256: string;
            /** @description Parent versions: the current head, plus the client's own parent for a merge (dropped if it no longer exists, e.g. a pruned autosave). Empty for a document's first version. */
            parentIds: null | string[];
            /** @description Optional thumbnail blob: PNG or WebP, at most 512×512 pixels and 256 KiB. */
            thumbnailSha256: null | string;
        };
        PasswordResetLinkResponse: {
            /**
             * Format: date-time
             * @description When the link stops working (UTC).
             */
            expiresAt: string;
            /** @description Link to the web app's reset page; single use. */
            resetUrl: string;
        };
        ProblemDetails: {
            detail?: null | string;
            instance?: null | string;
            /** Format: int32 */
            status?: number | null;
            title?: null | string;
            type?: null | string;
        };
        ResetPasswordRequest: {
            /** @description At least 10 characters, not a common password. */
            newPassword: string;
            /** @description From the reset link. */
            token: string;
            /**
             * Format: uuid
             * @description From the reset link.
             */
            userId: string;
        };
        SessionResponse: {
            /**
             * Format: date-time
             * @description Sign-in time (UTC).
             */
            createdAt: string;
            /** @description Whether this is the session making the request. */
            current: boolean;
            /**
             * Format: date-time
             * @description When the session ends unless used again (UTC).
             */
            expiresAt: string;
            /**
             * Format: uuid
             * @description Session id.
             */
            id: string;
            /** @description IP address the session was created from. */
            ipAddress: null | string;
            /**
             * Format: date-time
             * @description Last request (UTC, minute resolution).
             */
            lastSeenAt: string;
            /** @description User agent of the device that signed in. */
            userAgent: null | string;
        };
        SignUpRequest: {
            displayName: string;
            email: string;
            password: string;
        };
        StorageLimits: {
            /** @description How long autosaves are kept (for the history view). */
            autosaveRetention: components["schemas"]["AutosaveRetentionPolicy"];
            /**
             * Format: int64
             * @description Largest manifest a version may reference.
             */
            maxManifestBytes: number;
            /**
             * Format: int64
             * @description Largest blob upload (uncompressed).
             */
            maxUploadBytes: number;
            /**
             * Format: int64
             * @description Storage per user; `null` when unlimited.
             */
            quotaBytes: number | null;
            /**
             * Format: int32
             * @description Days before documents in the trash are deleted permanently.
             */
            trashRetentionDays: number;
        };
        StorageUsageResponse: {
            /**
             * Format: int64
             * @description The limit; `null` when unlimited.
             */
            quotaBytes: number | null;
            /**
             * Format: int64
             * @description Unique blobs referenced by the user's versions (trash included) or recently uploaded, uncompressed.
             */
            usedBytes: number;
        };
        /** Format: binary */
        Stream: Blob;
        UpdateDocumentRequest: {
            /** @description New display name, 1–200 characters. */
            name: string;
        };
        UpdateMeRequest: {
            /** @description New display name; omitted or `null` keeps the current one. */
            displayName: null | string;
        };
        UpdateVersionRequest: {
            /** @description New label; an empty string removes it; omitted or `null` keeps it. */
            label: null | string;
            /** @description Pin (never pruned) or unpin; omitted or `null` keeps it. */
            pinned: null | boolean;
        };
        UserSettings: {
            autosave?: components["schemas"]["AutosaveSettings"];
        };
        VerifyEmailRequest: {
            /** @description From the verification link. */
            token: string;
            /**
             * Format: uuid
             * @description From the verification link.
             */
            userId: string;
        };
        /** @enum {unknown} */
        VersionKind: "manual" | "auto" | "merge" | "restore" | "mcp";
        VersionList: {
            /** @description The page, newest first. */
            items: components["schemas"]["VersionResponse"][];
            /** @description Pass as `cursor` for the next page; `null` on the last page. */
            nextCursor: null | string;
        };
        VersionResponse: {
            /** @description Saving client instance. */
            clientId: null | string;
            /**
             * Format: date-time
             * @description Save time (UTC, server clock).
             */
            createdAt: string;
            /** @description Saving device. */
            deviceName: null | string;
            /** @description Document id. */
            documentId: string;
            /**
             * Format: int32
             * @description Client document format of the manifest.
             */
            formatVersion: number;
            /**
             * Format: uuid
             * @description Version id (UUIDv7, server clock); versions are ordered by id.
             */
            id: string;
            /** @description Why it was saved. */
            kind: components["schemas"]["VersionKind"];
            /** @description Label, if any. */
            label: null | string;
            /** @description Manifest blob; the content is served by `GET /api/versions/{versionId}`. */
            manifestSha256: string;
            /** @description Parents: none for the first version (or when older autosaves were pruned), usually two for a merge. Pruning autosaves re-parents their children onto their parents. */
            parentIds: string[];
            /** @description Pinned versions are never pruned. */
            pinned: boolean;
            /**
             * Format: int64
             * @description Manifest plus referenced blobs, uncompressed, each counted once.
             */
            sizeBytes: number;
            /** @description Thumbnail blob, if any. */
            thumbnailSha256: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminGetSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSystemResponse"];
                };
            };
        };
    };
    AdminListUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
        };
    };
    AdminDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminDisableUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminEnableUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminCreatePasswordResetLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetLinkResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ConfirmEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChangeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ForgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    LogIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    LogOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    SignUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    VerifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UploadBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": components["schemas"]["Stream"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CheckBlobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlobCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlobCheckResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    ListDocuments: {
        parameters: {
            query?: {
                /** @description nextCursor of the previous page. */
                cursor?: string;
                /** @description Page size, 1-200 (default 50). */
                limit?: number;
                /** @description Case-insensitive name filter (substring). */
                q?: string;
                /** @description true: the documents in the trash; otherwise the others. */
                trash?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CreateDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key (1-128 printable ASCII characters, e.g. a UUID); retrying with the same key within 24 hours returns the original result. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    TrashDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RenameDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    RestoreDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListVersions: {
        parameters: {
            query?: {
                /** @description nextCursor of the previous page. */
                cursor?: string;
                /** @description Only versions of this kind: manual, auto, merge, restore or mcp. */
                kind?: string;
                /** @description Page size, 1-200 (default 50). */
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    SaveVersion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key (1-128 printable ASCII characters, e.g. a UUID); retrying with the same key within 24 hours returns the original result. */
                "Idempotency-Key"?: string;
                /** @description The head version id the save is based on (the document's ETag). */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewVersionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ChangeEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ExportAccount: {
        parameters: {
            query?: {
                /** @description true: every kept version of each document, not only the latest. */
                history?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    RevokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
        };
    };
    UpdateSettings: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the settings the change is based on; omit to overwrite whatever is stored. */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUsageResponse"];
                };
            };
        };
    };
    ListAccessTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"][];
                };
            };
        };
    };
    CreateAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccessTokenRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAccessTokenResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RevokeAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetVersionManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVersionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
}
