// Part of the Spicy3D Project, derived from Chili3D, under the AGPL-3.0 License.
// See LICENSE file in the project root for full license information.

import type { MergeRuleRegistry, MergeValueRule } from "./rules";

// Renders the rule registry as the generated section of docs/merge.md, so the spec's class list is
// the registry itself (`mergeRules.test.ts` fails when the file is stale; `npm run merge:rules`
// rewrites it).

export const MERGE_RULES_BEGIN =
    "<!-- merge-rules:begin (generated by `npm run merge:rules`, do not edit) -->";
export const MERGE_RULES_END = "<!-- merge-rules:end -->";

/** A one-line notation of a rule (no nesting beyond one level of `object` fields). */
export function formatMergeRule(rule: MergeValueRule): string {
    switch (rule.kind) {
        case "atomic":
            return rule.of === undefined ? "atomic" : `atomic of ${formatMergeRule(rule.of)}`;
        case "ref":
            return `ref → ${rule.target}`;
        case "timeline-position":
            return `timeline-position (body = ${rule.bodyFrom === "key" ? "map key" : "`nodeId`"})`;
        case "json":
            return `json → payload \`${rule.payload}\``;
        case "object": {
            const fields = Object.entries(rule.fields).map(([k, v]) => `${k}: ${formatMergeRule(v)}`);
            if (rule.rest !== undefined) fields.push(`…: ${formatMergeRule(rule.rest)}`);
            for (const [group, members] of Object.entries(rule.groups ?? {}))
                fields.push(`${group} = ${members.join(" + ")}`);
            return `${rule.atomic ? "atomic " : ""}{ ${fields.join("; ")} }`;
        }
        case "union":
            return `union on \`${rule.tag}\` (${[...Object.keys(rule.variants), ...(rule.fallback ? ["any other"] : [])].join(", ")})`;
        case "list":
            return `list of \`${rule.segment}\` by \`${rule.key}\` (${rule.order} order)`;
        case "map":
            return `map of ${formatMergeRule(rule.value)}`;
        default:
            return rule.kind;
    }
}

function escapeCell(text: string): string {
    return text.replaceAll("|", "\\|").replaceAll("\n", " ");
}

/** Nested bullet list of a payload rule: containers expand, leaves print inline. */
function renderRuleTree(rule: MergeValueRule, indent: string, lines: string[]): void {
    const child = `${indent}  `;
    switch (rule.kind) {
        case "object":
            if (rule.atomic) {
                lines.push(`${indent}- ${formatMergeRule(rule)}`);
                return;
            }
            for (const [name, field] of Object.entries(rule.fields)) {
                lines.push(`${indent}- \`${name}\`: ${formatMergeRule(field)}`);
                if (isContainer(field)) renderChildren(field, child, lines);
            }
            if (rule.rest !== undefined)
                lines.push(`${indent}- any other field: ${formatMergeRule(rule.rest)}`);
            for (const [group, fields] of Object.entries(rule.groups ?? {}))
                lines.push(
                    `${indent}- group \`${group}\` (one value): ${fields.map((f) => `\`${f}\``).join(", ")}`,
                );
            return;
        default:
            lines.push(`${indent}- ${formatMergeRule(rule)}`);
            renderChildren(rule, child, lines);
    }
}

function isContainer(rule: MergeValueRule): boolean {
    return (
        (rule.kind === "object" && !rule.atomic) ||
        rule.kind === "union" ||
        rule.kind === "list" ||
        (rule.kind === "map" && isContainer(rule.value))
    );
}

function renderChildren(rule: MergeValueRule, indent: string, lines: string[]): void {
    switch (rule.kind) {
        case "object":
            if (!rule.atomic) renderRuleTree(rule, indent, lines);
            return;
        case "union":
            for (const [tag, variant] of Object.entries(rule.variants)) {
                lines.push(`${indent}- \`${rule.tag}: "${tag}"\``);
                renderRuleTree(variant, `${indent}  `, lines);
            }
            if (rule.fallback !== undefined) {
                lines.push(`${indent}- any other \`${rule.tag}\``);
                renderRuleTree(rule.fallback, `${indent}  `, lines);
            }
            return;
        case "list":
            renderRuleTree(rule.item, indent, lines);
            return;
        case "map":
            if (isContainer(rule.value)) renderChildren(rule.value, indent, lines);
            return;
        default:
            return;
    }
}

/**
 * The generated section of docs/merge.md: one table row per class (sorted), then every payload
 * rule as a tree. Deterministic for a given registry.
 */
export function renderMergeRules(registry: MergeRuleRegistry): string {
    const lines: string[] = [
        MERGE_RULES_BEGIN,
        "",
        "| Class | Strategy | Properties (beyond the defaults) | Why |",
        "|-------|----------|----------------------------------|-----|",
    ];
    for (const name of registry.classNames()) {
        const rule = registry.classRule(name)!;
        const key = rule.key === undefined ? "" : ` (key \`${rule.key}\`)`;
        const properties = Object.entries(rule.properties ?? {})
            .map(([property, value]) => `\`${property}\`: ${formatMergeRule(value)}`)
            .join("<br>");
        lines.push(
            `| \`${name}\` | ${rule.strategy}${key} | ${escapeCell(properties) || "—"} | ${escapeCell(rule.note)} |`,
        );
    }
    for (const name of registry.payloadNames()) {
        const payload = registry.payloadRule(name)!;
        const root = payload.segment === undefined ? "`node/<id>`" : `\`node/<id>/${payload.segment}\``;
        lines.push("", `#### Payload \`${name}\``, "", `${payload.note} Paths below ${root}.`, "");
        renderRuleTree(payload.rule, "", lines);
    }
    lines.push("", MERGE_RULES_END);
    return lines.join("\n");
}
